<?php

/**
 * @file
 * Contains fixerio.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fixerio_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fixerio module.
    case 'help.page.fixerio':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Fixer.io exchange rates and corrency conversion JSON API') . '</p>';
      $output .= '<p>' . t('Usage example: %example', [
        '%example' => '\Drupal::service("fixerio.exchange")->convert(2.90, "USD", "EUR");'
        ]) . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function fixerio_cron() {
  $logger = Drupal::logger('fixerio');
  $time = \Drupal::time()->getRequestTime();
  /** @var \Drupal\fixerio\FixerioApiInterface $api */
  $api = \Drupal::service('fixerio.api');
  $expires = \Drupal::state()
    ->get('fixerio.rates_check', 0);
  $config = \Drupal::config('fixerio.settings');
  $interval = $config->get('refresh');
  $interval = !empty($interval) ? $interval : 3600;


  if ($time >= $expires) {
    $logger->notice('Fixer.io cron ran');
    $api->latest();
    \Drupal::state()
      ->set('fixerio.rates_check', $time + $interval);
  }
}

/**
 * Implements hook_views_data().
 */
function fixerio_views_data() {
  $data = [];

  $data['fixerio_exchange'] = [];
  $data['fixerio_exchange']['table'] = [];
  $data['fixerio_exchange']['table']['group'] = t('Fixer.io');
  $data['fixerio_exchange']['table']['provider'] = 'fixerio';
  $data['fixerio_exchange']['table']['base'] = [
    'field' => 'id',
    'title' => t('Fixer.io rates'),
    'help' => t('List of exchange rates fixer.io.'),
    'weight' => -10,
  ];

  $data['fixerio_exchange']['base'] = [
    'title' => t('Base currency'),
    'help' => t('Base currency code'),
    'field' => [
      'id' => 'standard',
    ],
    'sort' => [
      'id' => 'standard',
    ],
    'filter' => [
      'id' => 'string',
    ],
    'argument' => [
      'id' => 'string',
    ],
  ];

  $data['fixerio_exchange']['code'] = [
    'title' => t('Currency'),
    'help' => t('Currency code'),
    'field' => [
      'id' => 'standard',
    ],
    'sort' => [
      'id' => 'standard',
    ],
    'filter' => [
      'id' => 'string',
    ],
    'argument' => [
      'id' => 'string',
    ],
  ];
  $data['fixerio_exchange']['rate'] = [
    'title' => t('Rate value'),
    'help' => t('Rate value (float).'),
    'field' => [
      'id' => 'numeric',
    ],
    'sort' => [
      'id' => 'standard',
    ],
    'filter' => [
      'id' => 'numeric',
    ],
    'argument' => [
      'id' => 'numeric',
    ],
  ];

  $data['fixerio_exchange']['created'] = [
    'title' => t('Created timestamp'),
    'help' => t('Created timestamp'),
    'field' => [
      'id' => 'date',
    ],
    'sort' => [
      'id' => 'date',
    ],
    'filter' => [
      'id' => 'date',
    ],
  ];
  return $data;
}
