<?php

/**
 * @file
 * Contains fixerio.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fixerio_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fixerio module.
    case 'help.page.fixerio':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Fixer.io exchange rates and corrency conversion JSON API') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function fixerio_theme() {
  return [
    'fixerio' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function fixerio_cron() {
  $logger = Drupal::logger('fixerio');
  $time = \Drupal::time()->getRequestTime();
  /** @var \Drupal\fixerio\FixerioApiInterface $api */
  $api = \Drupal::service('fixerio.api');
  $expires = \Drupal::state()
    ->get('fixerio.rates_check', 0);
  $config = \Drupal::config('fixerio.settings');
  $interval = $config->get('interval');
  $interval = !empty($interval) ? $interval : 3600;


  if ($time >= $expires) {
    $logger->notice('fixerio_cron ran');
    $api->latest();
    \Drupal::state()
      ->set('fixerio.rates_check', $time + $interval);
  }
}
