fixerio.settings:
  type: config_object
  label: 'Fixer.io settings'
  mapping:
    plan:
      type: string
      label: 'Plan'
    api_access_key:
      type: string
      label: 'API key'
    base:
      type: string
      label: 'Base currency'
    refresh:
      type: integer
      label: Refresh interval
    available_currencies:
      type: sequence
      label: 'Available currencies'
      sequence:
        type: string
        label: 'Currency'
